### ISSUE TITLE
No retry and hangs when connection to Elasticsearch times out

### ISSUE THREAD

**Issue by centic9** [centic9/elasticsearch-reindex-tool#1]
Seem to get this consistently, processing hangs at this point and does not stop or progress further...

```
10:25:57.708 [pool-1-thread-1] INFO  p.a.t.s.e.t.r.s.ProcessStatistics - PT1H4M13.963S items: 5983200 / 5988000 (1 1) failed=0
10:25:58.954 [pool-1-thread-1] INFO  p.a.t.s.e.t.r.s.ProcessStatistics - PT1H4M15.209S items: 5985600 / 5990400 (1 1) failed=0
10:26:00.948 [pool-1-thread-1] INFO  p.a.t.s.e.t.r.s.ProcessStatistics - PT1H4M17.203S items: 5988000 / 5992800 (1 1) failed=0
10:26:02.900 [pool-1-thread-1] INFO  p.a.t.s.e.t.r.s.ProcessStatistics - PT1H4M19.155S items: 5990400 / 5995200 (1 1) failed=0
10:26:10.041 [elasticsearch[Amber Hunt][generic][T#16]] INFO  org.elasticsearch.client.transport - [Amber Hunt] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [3253] timed out after [5000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
10:26:10.041 [elasticsearch[Amber Hunt][generic][T#16]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
10:26:13.187 [elasticsearch[Masked Marvel][generic][T#14]] INFO  org.elasticsearch.client.transport - [Masked Marvel] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [3250] timed out after [5002ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
10:26:13.187 [elasticsearch[Masked Marvel][generic][T#14]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
10:26:15.165 [elasticsearch[Amber Hunt][generic][T#16]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
10:26:18.297 [elasticsearch[Masked Marvel][generic][T#14]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
10:26:23.766 [elasticsearch[Amber Hunt][generic][T#16]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
10:26:25.209 [elasticsearch[Masked Marvel][generic][T#14]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
10:26:30.400 [elasticsearch[Amber Hunt][generic][T#25]] INFO  org.elasticsearch.client.transport - [Amber Hunt] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [3256] timed out after [5002ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
10:26:30.400 [elasticsearch[Amber Hunt][generic][T#25]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
10:26:33.518 [elasticsearch[Masked Marvel][generic][T#26]] INFO  org.elasticsearch.client.transport - [Masked Marvel] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [3253] timed out after [5000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
10:26:33.519 [elasticsearch[Masked Marvel][generic][T#26]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
10:26:35.510 [elasticsearch[Amber Hunt][generic][T#25]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
10:26:35.738 [elasticsearch[Amber Hunt][generic][T#25]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
10:26:38.637 [elasticsearch[Masked Marvel][generic][T#26]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
10:26:38.868 [elasticsearch[Masked Marvel][generic][T#26]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:12.213 [elasticsearch[Amber Hunt][generic][T#55]] INFO  org.elasticsearch.client.transport - [Amber Hunt] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5080] timed out after [5000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:02:12.214 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:02:14.694 [elasticsearch[Masked Marvel][generic][T#26]] INFO  org.elasticsearch.client.transport - [Masked Marvel] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5077] timed out after [5001ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:02:14.694 [elasticsearch[Masked Marvel][generic][T#26]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:02:17.327 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:19.806 [elasticsearch[Masked Marvel][generic][T#26]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:24.484 [elasticsearch[Masked Marvel][generic][T#26]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
13:02:25.143 [elasticsearch[Masked Marvel][generic][T#77]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:27.991 [elasticsearch[Amber Hunt][generic][T#71]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
13:02:32.554 [elasticsearch[Amber Hunt][generic][T#55]] INFO  org.elasticsearch.client.transport - [Amber Hunt] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5083] timed out after [5001ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:02:32.555 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:02:35.149 [elasticsearch[Masked Marvel][generic][T#78]] INFO  org.elasticsearch.client.transport - [Masked Marvel] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5080] timed out after [5002ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:02:35.149 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:02:37.683 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:37.934 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:40.259 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:02:45.808 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
13:02:50.709 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
13:09:11.794 [elasticsearch[Amber Hunt][generic][T#55]] INFO  org.elasticsearch.client.transport - [Amber Hunt] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5160] timed out after [5000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:09:11.794 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:09:14.261 [elasticsearch[Masked Marvel][generic][T#78]] INFO  org.elasticsearch.client.transport - [Masked Marvel] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5157] timed out after [5000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:09:14.261 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:09:16.904 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:09:19.371 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:09:24.623 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
13:09:28.118 [elasticsearch[Amber Hunt][generic][T#84]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}], channel closed event
13:09:32.132 [elasticsearch[Amber Hunt][generic][T#55]] INFO  org.elasticsearch.client.transport - [Amber Hunt] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5163] timed out after [5001ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:09:32.132 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:09:34.598 [elasticsearch[Masked Marvel][generic][T#78]] INFO  org.elasticsearch.client.transport - [Masked Marvel] failed to get node info for {#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][es/1.1.1.1:9300][cluster:monitor/nodes/liveness] request_id [5160] timed out after [5000ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:645) ~[elasticsearch-2.1.0.jar:2.1.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
13:09:34.598 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] disconnecting from [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}] due to explicit disconnect call
13:09:37.251 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:09:37.481 [elasticsearch[Amber Hunt][generic][T#55]] DEBUG org.elasticsearch.transport.netty - [Amber Hunt] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
13:09:39.707 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{#transport#-1}{1.1.1.1}{es/1.1.1.1:9300}]
13:09:39.949 [elasticsearch[Masked Marvel][generic][T#78]] DEBUG org.elasticsearch.transport.netty - [Masked Marvel] connected to node [{es-perform-main}{qSuWGRzlQS63XlsvhmmGng}{1.1.1.1}{es/1.1.1.1:9300}]
```

**Comment by centic9** [comment]
Did not happen again...
